Repository appsignal/mono, pull requests merged in 2023-05, with the labels that each got.

#52 Support custom languages
  .changesets/support-custom-languages.md
  README.md
  lib/mono/command.rb
  lib/mono/language.rb
  lib/mono/languages.rb
  lib/mono/languages/custom/language.rb
  lib/mono/languages/custom/package.rb
  lib/mono/package.rb
  spec/lib/mono/cli/publish/custom_spec.rb
Labels: feature

#55 Omit ci skip tag from publish commit
  .changesets/remove-skip-ci-tag-from-publish-commit.md
  lib/mono/cli/publish.rb
  spec/lib/mono/cli/publish/base_spec.rb
  spec/lib/mono/cli/publish/custom_spec.rb
  spec/lib/mono/cli/publish/elixir_spec.rb
  spec/lib/mono/cli/publish/nodejs_spec.rb
  spec/lib/mono/cli/publish/ruby_spec.rb
Labels: chore

#56 Improve publish commit message
  .changesets/improve-publish-commit-message.md
  lib/mono/cli/publish.rb
  spec/lib/mono/cli/publish/base_spec.rb
  spec/lib/mono/cli/publish/custom_spec.rb
  spec/lib/mono/cli/publish/elixir_spec.rb
  spec/lib/mono/cli/publish/nodejs_spec.rb
  spec/lib/mono/cli/publish/ruby_spec.rb
Labels: enhancement

#57 Implement Python version scheme
  lib/mono/config.rb
  lib/mono/languages/custom/package.rb
  lib/mono/languages/elixir/package.rb
  lib/mono/languages/nodejs/package.rb
  lib/mono/languages/ruby/package.rb
  lib/mono/version_object.rb
  lib/mono/version_promoter.rb
  spec/lib/mono/cli/publish/custom_spec.rb
  spec/lib/mono/languages/elixir/package_spec.rb
  spec/lib/mono/version_promoter_spec.rb
  spec/lib/mono/version_spec.rb
Labels: enhancement
