Repository appsignal/mono, pull requests merged in 2024-07, with the labels that each got.

#78 Mono auto update
  .changesets/add-auto-update-functionality.md
  bin/mono
  lib/mono/cli.rb
  lib/mono/cli/init.rb
Labels: enhancement

#79 Refactor the changeset collection specs
  spec/lib/mono/changeset_collection_spec.rb
  spec/support/helpers/project_helper.rb
Labels: dev happiness

#80 List multiple commits in changelog per entry
  .changesets/list-all-relevant-commits-in-changelog.md
  .changesets/skip-commtis-for-changeset-commit-sha.md
  lib/mono/changeset.rb
  lib/mono/changeset_collection.rb
  spec/lib/mono/changeset_collection_spec.rb
  spec/lib/mono/changeset_spec.rb
  spec/support/helpers/git_helper.rb
Labels: enhancement

#81 Fix bug for changesets without commit
  .changesets/fix-error-on-changeset-without-commit.md
  lib/mono/changeset.rb
  spec/lib/mono/changeset_collection_spec.rb
  spec/lib/mono/changeset_spec.rb
  spec/support/helpers/changeset_helper.rb
Labels: bug
